// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Purchase struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Suplier   string
	Price     int32
	Quantity  int32
	GrainType string
}

type Receipt struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	TruckReg   string
	TrailerReg string
	Gross      int32
	Tare       int32
	Net        int32
	DocType    string
	GrainType  string
	PurchaseID sql.NullInt32
}
