// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: purchases.sql

package database

import (
	"context"
	"time"
)

const createPurchase = `-- name: CreatePurchase :exec
INSERT INTO purchases (
    created_at, updated_at, suplier, price, quantity, grain_type 
    )
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
`

type CreatePurchaseParams struct {
	Suplier   string
	Price     int32
	Quantity  int32
	GrainType string
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) error {
	_, err := q.db.ExecContext(ctx, createPurchase,
		arg.Suplier,
		arg.Price,
		arg.Quantity,
		arg.GrainType,
	)
	return err
}

const getAllPurchases = `-- name: GetAllPurchases :many
SELECT p.id, p.created_at, p.updated_at, p.suplier, p.price, p.quantity, p.grain_type, SUM(r.net) AS expedited 
FROM purchases p
LEFT JOIN receipts r
ON p.id = r.purchase_id
GROUP BY p.id
`

type GetAllPurchasesRow struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Suplier   string
	Price     int32
	Quantity  int32
	GrainType string
	Expedited int64
}

func (q *Queries) GetAllPurchases(ctx context.Context) ([]GetAllPurchasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPurchases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPurchasesRow
	for rows.Next() {
		var i GetAllPurchasesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Suplier,
			&i.Price,
			&i.Quantity,
			&i.GrainType,
			&i.Expedited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseById = `-- name: GetPurchaseById :one
SELECT id, created_at, updated_at, suplier, price, quantity, grain_type FROM purchases
WHERE id = $1
`

func (q *Queries) GetPurchaseById(ctx context.Context, id int32) (Purchase, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseById, id)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Suplier,
		&i.Price,
		&i.Quantity,
		&i.GrainType,
	)
	return i, err
}
