// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: purchases.sql

package database

import (
	"context"
)

const createPurchase = `-- name: CreatePurchase :exec
INSERT INTO purchases (
    created_at, updated_at, suplier, price, quantity, grain_type 
    )
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
`

type CreatePurchaseParams struct {
	Suplier   string
	Price     int32
	Quantity  int32
	GrainType string
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) error {
	_, err := q.db.ExecContext(ctx, createPurchase,
		arg.Suplier,
		arg.Price,
		arg.Quantity,
		arg.GrainType,
	)
	return err
}

const getAllPurchases = `-- name: GetAllPurchases :many
SELECT id, created_at, updated_at, suplier, price, quantity, grain_type FROM purchases
`

func (q *Queries) GetAllPurchases(ctx context.Context) ([]Purchase, error) {
	rows, err := q.db.QueryContext(ctx, getAllPurchases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Purchase
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Suplier,
			&i.Price,
			&i.Quantity,
			&i.GrainType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
