// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: purchases.sql

package database

import (
	"context"
)

const createPurchase = `-- name: CreatePurchase :exec
INSERT INTO purchases (
    created_at, updated_at, suplier, price, quantity, grain_type 
    )
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
`

type CreatePurchaseParams struct {
	Suplier   string
	Price     int32
	Quantity  int32
	GrainType string
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) error {
	_, err := q.db.ExecContext(ctx, createPurchase,
		arg.Suplier,
		arg.Price,
		arg.Quantity,
		arg.GrainType,
	)
	return err
}
