-- +goose Up
CREATE TABLE receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    truck_reg TEXT NOT NULL,
    trailer_reg TEXT NOT NULL,
    gross INT NOT NULL,
    tare INT NOT NULL,
    net INT NOT NULL
);

-- +goose Down
DROP TABLE receipts;