-- +goose Up
CREATE TABLE purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    suplier TEXT NOT NULL,
    price INT NOT NULL,
    quantity INT NOT NULL,
    grain_type TEXT NOT NULL
);

-- +goose Down
DROP TABLE purchases;