-- +goose Up
CREATE TABLE sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    client TEXT NOT NULL,
    price INT NOT NULL,
    quantity INT NOT NULL,
    grain_type TEXT NOT NULL
);

ALTER TABLE receipts
ADD COLUMN sale_id INT REFERENCES sales(id);

-- +goose Down

ALTER TABLE receipts
DROP COLUMN sale_id;

DROP TABLE sales;