-- +goose Up
CREATE TABLE transports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    truck_reg TEXT NOT NULL,
    trailer_reg TEXT NOT NULL,
    net INT NOT NULL,
    grain_type TEXT NOT NULL,
    sale_id INT REFERENCES sales(id),
    purchase_id INT REFERENCES purchases(id)
);

-- +goose Down
DROP TABLE transports;